[versions]
slf4j-version = "2.0.0-alpha1"
logback-version = "1.3.0-alpha4"
jsch-version = "0.1.55"
picocli-version = "4.6.1"
jackson-version = "2.12.2"
raksrinana-utils-version = "15.0.2"
commons-io-version = "2.8.0"
progressbar-version = "0.9.1"
jetbrains-annotations-version = "20.1.0"

[libraries]
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-version" }
jsch = { group = "com.jcraft", name = "jsch", version.ref = "jsch-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
raksrinana-utils-base = { group = "fr.raksrinana", name = "utils.base", version.ref = "raksrinana-utils-version" }
raksrinana-utils-config = { group = "fr.raksrinana", name = "utils.config", version.ref = "raksrinana-utils-version" }
commonsIo = { group = "commons-io", name = "commons-io", version.ref = "commons-io-version" }
progressbar = { group = "me.tongfei", name = "progressbar", version.ref = "progressbar-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }


[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
raksrinanaUtils = ["raksrinana-utils-base", "raksrinana-utils-config"]
